### ISSUE TITLE
Push Fehler wegen mehreren Teilnehmern

### ISSUE THREAD

**Issue by wyrnat** [VakuumSchwadron/Mediathek#2]
Wenn mehrere Teilnehmer an einem Projekt arbeiten, kann man nicht einfach mit Commit&Push
hochladen. Man muss zuerst mit pull vergewisern, dass die lokale Version mit der Github-Version identisch ist. Wenn nicht, wird dies durch pull (herunterziehen des aktuellen branches) korrigiert.

Hat mich etwas Zeit gekostet, also nicht nochmal den Fehler machen

**Comment by barbieauglend** [comment]
Ja, es ist auch wichtig, dass jeder für sich arbeitet und in Orga erstmal nur hochlädt. Und bevor man anfängt was zu ändern, kann man die aktuelle Version anschauen - ggf die Änderung der anderen "autorisieren", runterladen, und dann arbeiten. Dann sind wir immer up-to-date ;)
